AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30
    Runtime: go1.x
    Architectures:
      - x86_64
Resources:
  UploadProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upload-product
      Handler: uploadProduct
      CodeUri: ./cmd/uploadProduct/
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post
      Environment:
        Variables:
          POSTGRES_URL: postgres://product-lambda:product123@localhost:5432/products?sslmode=disable
          REDIS_ADDR: localhost:6379

  GetAllProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-all-products
      Handler: getAllProducts
      CodeUri: ./cmd/getAllProducts/
      Events:
        ProductsApi:
          Type: Api
          Properties:
            Path: /products
            Method: get
      Environment:
        Variables:
          POSTGRES_URL: postgres://product-lambda:product123@localhost:5432/products?sslmode=disable
          REDIS_ADDR: localhost:6379
